import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

import Providers from './Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props ) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
