// Generated by https://quicktype.io

export interface ApiResponse {
    succeeded: boolean;
    message:   string;
    errors:    string[];
    data?:      {};
}

export interface LoginResponse {
    id:         string;
    userName:   string;
    email:      string;
    roles:      string[];
    clientId:   number;
    isVerified: boolean;
    refreshToken?: string;
    jwtToken:   string;
    hasError:   boolean;
    error:      string;
}
